export const PROJECT_SETTINGS: string[];
export const USER_SETTINGS: string[];
export const RETIRED_SETTINGS: { project: Record<string, string>; user: Record<string, string> };
export function settingsKeys(settings: unknown, known: string[], retired?: Record<string, string>): { unknown: Array<{ key: string; suggestion?: string }>; retired: Array<{ key: string; instead: string }> };
export function settingsWarnings(settings: unknown, scope: 'project' | 'user'): string[];
export function validateSettings(settings: unknown, source: string): { provider?: string; model?: string; reasoning?: string };
export function validateUserSettings(settings: unknown, source: string): { language?: string; permissions?: unknown; limits?: { autoResume?: boolean }; recovery?: { autoResume?: boolean } };
export function normalizeMcp(raw: unknown, directory: string, source: string): { mcpServers: Record<string, Record<string, unknown>> };
export function validateResolvedAgent(agent: unknown): unknown;
export const AGENT_SETTINGS: string[];
export function validateAgentConfig(config: unknown, source: string): { description?: string; provider?: string; model?: string; thinking?: string; mode?: 'read-only' | 'workspace-write' | 'full-access'; skills?: string[]; mcp?: string[]; hooks?: string[] };
export const HOOK_SETTINGS: string[];
export const HOOK_EVENTS: string[];
export const BLOCKING_HOOK_EVENTS: string[];
export function validateHook(config: unknown, source: string): { description?: string; event: string; command: string; blocking?: boolean; timeoutSec?: number; match?: { agent?: string; label?: string } };
export function unknownMessage(unknown: { key: string; suggestion?: string }, known: string[]): string;
